language: rust
rust:
  - 1.39.0
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
matrix:
  include:
    - rust: 'stable'
      env:
        - RUST_BACKTRACE=1 RUN_CLIPPY=true RUN_RUSTFMT=true

script: ./scripts/build_and_test.sh
