language: rust
rust:
  - 1.32.0
  - stable
  - beta
  - nightly
env:
  - RUST_BACKTRACE=1
script:
- rustup component add clippy
- rustup component add rustfmt
- cargo fmt --all -- --check
- cargo build
- cargo clippy --all
- cargo test --verbose
