[package]
name = "bita"
version = "0.1.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]

[dependencies]
docopt = "1.0.2"
sha2 = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
flate2 = "*"
rust-lzma = "*"
threadpool = "*"
num_cpus = "0.2"
