[package]
name = "bita"
version = "0.3.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "Differential file synchronization over http(s)."
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["update", "swupdate", "synchronization", "delta-update"]
categories = ["command-line-utilities", "compression", "differential"]

[build-dependencies]
protoc-rust = "2.8.1"

[dependencies]
clap = "2.33.0"
threadpool = "1.7.1"
num_cpus = "1.10.1"
curl = "0.4.25"
blake2 = "0.8.1"
atty = "0.2.13"
protobuf = "2.8.1"
crossbeam-channel = "0.3.9"
log = "0.4.8"
fern = "0.5.8"
chrono = "0.4.9"
brotli = "3.3.0"
rust-lzma = {version = "0.4.0", optional = true}
zstd = {version = "0.4.28", optional = true }
futures-preview = {version = "0.3.0-alpha.19", features = ["compat", "async-await", "io-compat"] }
tokio = "0.2.0-alpha.6"
futures-cpupool = "0.1.8"

[features]
default = []
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
