[package]
name = "bita"
version = "0.1.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"

[dependencies]
clap = "*"
sha2 = "*"
serde = "*"
serde_derive = "*"
bincode = "*"
rust-lzma = "*"
threadpool = "*"
num_cpus = "0.2"
curl = "*"
