[package]
name = "bitar"
version = "0.5.0"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "bita archive utilities"
repository = "https://github.com/oll3/bita"

[build-dependencies]
protoc-rust = "2.10"

[dependencies]
blake2 = "0.8"
protobuf = "2.10"
log = "0.4"
brotli = "3.3"
futures-core = {version = "0.3" }
futures-util = {version = "0.3" }
tokio = { version = "0.2", features = ["fs", "io-std", "sync", "io-util", "macros", "time", "rt-threaded"] }
hyper = { version = "0.13", features = ["stream"] }
hyper-rustls = "0.19"

rust-lzma = {version = "0.5", optional = true}
zstd = {version = "0.5", optional = true }

[dev-dependencies]
tempfile = "3.1"

[features]
default = []
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
