[package]
name = "bitar"
version = "0.7.1"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "bita archive utilities"
repository = "https://github.com/oll3/bita"
readme = "README.md"
keywords = ["sofware-update", "file-synchronization", "delta-update",  "differential"]
categories = ["compression", "filesystem"]


[build-dependencies]
prost-build = "0.7"

[dependencies]
blake2 = "0.9"
prost = "0.7"
log = "0.4"
brotli = "3.3"
futures-util = { version = "0.3", default-features = false }
tokio = "1.0"
bytes = "1.0"
rust-lzma = { version = "0.5", optional = true }
zstd = { version = "0.6", optional = true }
async-trait = "0.1"

[dev-dependencies]
tempfile = "3.1"
tokio = { version = "1.0", features = ["fs", "macros", "rt-multi-thread"] }
hyper = { version = "0.14", features = ["server"] }

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["stream"]

[features]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
