[package]
name = "bitar"
version = "0.5.1"
authors = ["Olle Sandberg <olle@b3rg.se>"]
license = "MIT"
edition = '2018'
description = "bita archive utilities"
repository = "https://github.com/oll3/bita"

[build-dependencies]
prost-build = "0.6"

[dependencies]
blake2 = "0.8"
prost = "0.6"
log = "0.4"
brotli = "3.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "0.2", features = ["fs", "io-std", "sync", "io-util", "macros", "time", "rt-threaded"] }
async-stream = "0.2"
bytes = "0.5"
rust-lzma = { version = "0.5", optional = true }
zstd = { version = "0.5", optional = true }

[dev-dependencies]
tempfile = "3.1"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["stream"]

[features]
default-tls = ["reqwest/default-tls"]
rustls-tls = ["reqwest/rustls-tls"]
lzma-compression = ["rust-lzma"]
zstd-compression = ["zstd"]
