on: push

name: CI

jobs:
  ci:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.51.0

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build

      - uses: actions-rs/cargo@v1
        name: test
        with:
          command: test
          args: --workspace --verbose

      - uses: actions-rs/cargo@v1
        name: test lzma/zstd
        with:
          command: test
          args: --workspace --verbose --features lzma-compression,zstd-compression

      - uses: actions-rs/cargo@v1
        name: check formatting
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: check lints
        with:
          command: clippy
          args: --all -- -D warnings -A clippy::cognitive-complexity

      - name: Verify build without libssl
        run: ./scripts/test-no-ssl-build.sh